Updates

diff --git a/mk-ovpn b/mk-ovpn
--- a/mk-ovpn
+++ b/mk-ovpn
@@ -14,48 +14,56 @@
 # can be used as intermediate CA certificates or direct validation. If this
 # is a problem the V3 certificates with the CA constraint should be used.
 
+do_commonname() {
+    CN="$1"
+    mkdir -p -m 700 "$CERT_DIR"
+    CAFILE="$CERT_DIR"/"$CN".ca.crt
+
+    [ "$CERTTYPE" = server ] &&
+	CAFILE="$CERT_DIR"/"$CN".ca.cer
+
+    [ -s "$CAFILE" ] && { echo "ERROR: Name '$CN' already exists" ; return ; }
+
+    mkc() {
+	./mk-cert -suca ${CERT_DAYS:+-days="$CERT_DAYS"} "$CN" "$@" > "$CAFILE"
+    }
+
+    if [ "$CERTTYPE" = '' ]
+    then if [ "$CERTVER" = v1 ]
+	 then mkc
+	 else mkc -v3critical
+	 fi
+    else
+	if [ "$CERTVER" = v1 ]
+	then CF=''
+	elif [ "$CERTVER" = v3 ]
+	then CF="-v3critical -v3ns=$CERTTYPE"
+	else CF="-v3critical -$CERTTYPE"
+	fi
+	mkc -casubj="$CN" -casubj="OpenVPN $CERTTYPE CA" "OpenVPN $CERTTYPE" $CF
+    fi
+}
+
 CERT_DIR="${CERT_DIR:-certs}"
 CERTVER=v1 ; CERTTYPE=
 
-for v
-do  case "$v" in
-    -s|-server ) CERTTYPE=server ;;
-    -c|-client ) CERTTYPE=client ;;
-    -v1 ) CERTVER=v1 ;;
-    -v3 ) CERTVER=v3 ;;
-    -v3ext ) CERTVER=v3x ;;
+for e in n y
+do
+    for v
+    do  case "$v" in
+	-s|-server ) CERTTYPE=server ;;
+	-c|-client ) CERTTYPE=client ;;
+	-v1 ) CERTVER=v1 ;;
+	-v3 ) CERTVER=v3 ;;
+	-v3ext ) CERTVER=v3x ;;
 
-    -days=[1-9]*[0-9] ) CERT_DAYS="${v#*=}" ;;
-    -dir=* )            CERT_DIR="${v#*=}" ;;
+	-days=[1-9]*[0-9] ) CERT_DAYS="${v#*=}" ;;
+	-dir=* )            CERT_DIR="${v#*=}" ;;
 
-    -* ) echo >&2 "Option $v not recognised"; exit 1;;
+	-* ) echo >&2 "Option $v not recognised"; exit 1;;
 
-    * ) [ "$CN" != '' ] && CN="$CN $v" || CN="$v" ;;
-    esac
+	*)  [ "$e" = y ] && do_commonname "$v"
+	    ;;
+	esac
+    done
 done
-
-CAFILE="$CERT_DIR"/"$CN".ca.crt
-
-[ "$CERTTYPE" = server ] &&
-    CAFILE="$CERT_DIR"/"$CN".ca.cer
-
-[ -s "$CAFILE" ] && { echo "ERROR: Name '$CN' already exists" ; exit 1 ; }
-
-mkc() {
-    ./mk-cert -suca ${CERT_DAYS:+-days="$CERT_DAYS"} "$CN" "$@" > "$CAFILE"
-}
-
-if [ "$CERTTYPE" = '' ]
-then if [ "$CERTVER" = v1 ]
-     then mkc
-     else mkc -v3critical
-     fi
-else
-    if [ "$CERTVER" = v1 ]
-    then CF=''
-    elif [ "$CERTVER" = v3 ]
-    then CF="-v3critical -v3ns=$CERTTYPE"
-    else CF="-v3critical -$CERTTYPE"
-    fi
-    mkc -casubj="$CN" -casubj="OpenVPN $CERTTYPE CA" "OpenVPN $CERTTYPE" $CF
-fi
