Merge mk-winset into updated mk-suca
Fixes for most recent OpenSSL
All variables made local
Change option processing to use -key=... option
Add option -pfx=... for Windows pfx output.
Workaround for *BSD's lack of packaging.

Also remove the mk-winset mini-script
and make-dom-svrkey

diff --git a/mk-suca b/mk-suca
--- a/mk-suca
+++ b/mk-suca
@@ -1,38 +1,98 @@
-#!/bin/bash
+#!/bin/sh
+# shellcheck shell=bash
 #
-# This script takes a file that contains a public key and creates
-# a certificate and single use CA certificate for the key.
+# This script takes a file that contains a public key and creates a
+# certificate and single use CA certificate for the key.  This public
+# key may be contained in a certificate, certificate request, private
+# key or in a file on it's own.
 #
-# This key may be contained in a certificate, certificate request,
-# private key or in a file on it's own.
+# The CA key is generated in such a way that it should be the same type
+# and size as the supplied key.
 #
-# Now also possible using: mk-cert -suca -pubin=keyfile.crt
+# The remaining arguments are the common name (default localhost) and
+# a list of SAN names.
 #
-# Process:
+# The output can be a pfx file, but if so the file specified with -key=...
+# must be a private key or the option omitted completely.
 #
-# The script then generates a second key to match the type of this
-# key and creates a CA certificate. This CA certificate (and key)
-# is used to create and sign a certificate for the public key, the
-# common name and SAN DNS names for the certificate are the remaining
-# arguments to the script.
-#
-# Finally the two generated certificates are output and the CA key
-# is discarded. If the key file name is '.' a key is generated and
-# the private key is output at the end.
-# 
+# You can do all this (except the automatic matching) with:
+#   mk-cert -suca -san -pubin=keyfile.crt hostname dnsnames...
+
+if [ -z "$BASH_VERSION" ];then exec bash "$0" "$@";else set +o posix;fi
 
 main() {
-    [ "$#" -lt 2 ] && {
-	echo >&2 "Usage: $0 keyfile common_name [san list]"
+    local ar KFNAME PFXNAME KEYFILE CAKEY PUBKEY SERIAL CERT CERTDAYS
+    local -a names
+
+    [ "$#" -lt 1 ] && {
+	echo >&2 "Usage: $0 [-key=keyfile.pem] [-pfx=file.pfx] common_name [san list]"
 	exit 1
     }
 
-    KFNAME="$1"
-    if [ "$KFNAME" = '.' ]
-    then KEYFILE="$(make_a_key /dev/null)"
-    else KEYFILE="$(cat "$KFNAME")"
+    for ar
+    do  case "$ar" in
+	-key=* )
+	    KFNAME="${ar#*[=:]}"
+	    KEYFILE="$(cat "$KFNAME")"
+	    ;;
+	-pfx=* ) PFXNAME="${ar#*[=:]}" ;;
+	-* ) echo >&2 "Unknown option '$ar'" ; exit 1 ;;
+	* ) names+=( "$ar" ) ;;
+	esac
+    done
+
+    [ "$KFNAME" = '' ] && {
+	if [ "$PFXNAME" != '' ]
+	then KEYFILE="$(openssl genrsa)"
+	else KEYFILE="$(openssl ecparam -name prime256v1 -genkey -noout)"
+	fi
+    }
+
+    [ "${#names}" = 0 ] && names+=( localhost )
+
+    [ -n "$KEYFILE" ] &&
+	PUBKEY=$(extract_pubkey "$KEYFILE")
+
+    [ "$PUBKEY" = '' ] && {
+	echo >&2 "Cannot find public key in $KFNAME, it needs to be unencrypted and in PEM format"
+	exit 1
+    }
+
+    [ "$CERTDAYS" = '' ] && {
+	CERTDAYS=$((24842 - $(date +%s)/86400))
+	[ "$CERTDAYS" -lt 3652 ] && CERTDAYS=3652
+    }
+
+    SERIAL="$(openssl rand -hex 8)"
+    CAKEY=$(make_ca "$PUBKEY" "$SERIAL" "${names[0]}")
+    CERT=$(make_cert "$CAKEY" "$SERIAL" "${names[@]}")
+
+    if [ -z "$PFXNAME" ]
+    then
+	echo "$CERT" | openssl x509 -subject -serial -dates
+	echo "$CAKEY" | openssl x509 -subject -serial -dates
+	[ "$KFNAME" = '' ] && echo "$KEYFILE"
+    else
+
+	openssl pkcs12 -export -passout "pass:" \
+	    -out "$PFXNAME" \
+	    -name "${names[1]} til: $(echo "$CERT" |
+				    openssl x509 -noout -enddate |
+				    sed -n 's/.*= *//p')" \
+	    -inkey <(echo "$KEYFILE") \
+	    -in <(echo "$CERT") \
+	    -certfile <(echo "$CAKEY" | openssl x509) \
+	    -caname "$(echo "$CAKEY" | openssl x509 -noout \
+		    -subject -nameopt multiline | sed -n 's/ *commonName *= //p'
+		    ) CA til: $(echo "$CAKEY" | openssl x509 -noout -enddate |
+		      sed -n 's/.*= *//p' )"
+
     fi
-    shift
+    exit 0
+}
+
+extract_pubkey() {
+    local PUBKEY PEMTYPE ITEM KEYFILE="$1"
 
     for PEMTYPE in x509 req pkey pubkey rsa ec dsa
     do
@@ -59,28 +119,11 @@ main() {
 	[ "$PUBKEY" = "" ] || break
     done
 
-    [ "$PUBKEY" = '' ] && {
-	echo >&2 "Cannot find public key in $KFNAME, it needs to be unencrypted and in PEM format"
-	exit 1
-    }
-
-    [ "$CERTDAYS" = '' ] && {
-	CERTDAYS=$((24842 - $(date +%s)/86400))
-	[ "$CERTDAYS" -lt 3652 ] && CERTDAYS=3652
-    }
-
-    CAKEY=$(make_ca)
-
-    make_cert "$@"
-
-    echo "$CAKEY" | openssl x509 -subject -serial -dates
-
-    [ "$KFNAME" = '.' ] && echo "$KEYFILE"
-    exit 0
+    echo "$PUBKEY"
 }
 
 make_ca() {
-    local SERIAL SSKEY SSCERT
+    local PUBKEY="$1" SERIAL SSKEY SSCERT
 
     SERIAL="$(openssl rand -hex 8)"
     SSKEY="$(make_a_key "$PUBKEY" )"
@@ -94,8 +137,9 @@ make_ca() {
 		echo 'prompt = no'
 		echo 'x509_extensions = x509v3'
 		echo '[rdn]'
-		echo "dnQualifier=$SERIAL"
-		echo "CN=Private CA"
+		[ "$2" != '' ] && echo "dnQualifier=$2"
+		echo "O=Above reproach CA"
+		echo "CN=$3"
 		echo '[x509v3]'
 		echo 'basicConstraints = CA:TRUE, pathlen:0'
 	    ) )"
@@ -105,8 +149,8 @@ make_ca() {
 }
 
 make_cert() {
-    local CN="$1" SERIAL NEWCERT
-    [ "$CN" = "" ] && CN=localhost
+    local CAKEY="$1" SERIAL="$2" CN="$3" NEWCERT
+    shift; shift
 
     make_cert_conf() {
 	local SANLIST=''
@@ -125,7 +169,7 @@ make_cert() {
 	}
     }
 
-    SERIAL="$(openssl rand -hex 8)"
+    [ "$SERIAL" = '' ] && SERIAL="$(openssl rand -hex 8)"
     TMPKEY="$(openssl ecparam -name prime256v1 -genkey -noout)"
     NEWCERT="$(openssl req -new \
 	    -key <(echo "$TMPKEY") \
@@ -141,7 +185,7 @@ make_cert() {
 
     unset -f make_cert_conf
 
-    echo "$NEWCERT" | openssl x509 -subject -serial -dates
+    echo "$NEWCERT"
 }
 
 make_a_key() {
@@ -162,7 +206,7 @@ make_a_key() {
 
     # Match the RSA bitsize of the key
     RSABITS=$(echo "$INKEY" | openssl rsa -pubin -text -noout 2>&1 |
-	awk '/^Public.Key: .*bit/{gsub("[^0-9]","",$2); print $2;}')
+	awk '/Public.Key: .*bit/{gsub("[^0-9]","",$0); print $0;}')
 
     # Do we have an RSA bit size ?
     [ "$RSABITS" != "" ] && {
@@ -172,7 +216,7 @@ make_a_key() {
 
     # Match the DSA bitsize of the key
     DSABITS=$(echo "$INKEY" | openssl dsa -pubin -text -noout 2>&1 |
-	awk '/^Public.Key: .*bit/{gsub("[^0-9]","",$2); print $2;}')
+	awk '/Public.Key: .*bit/{gsub("[^0-9]","",$0); print $0;}')
 
     DSALEN=$(echo "$INKEY" |
         openssl dsa -pubin -modulus -noout 2>/dev/null |
